/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.factorymanagement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author login
 */
public class AdminPanel extends javax.swing.JFrame {

    EmployeeClass adminData;
    ConnectionClass con = ConnectionClass.getInstance();

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    public AdminPanel(EmployeeClass adminData) {
        initComponents();
        this.adminData = adminData;
        String path = "C:\\Users\\login\\OneDrive\\Documents\\NetBeansProjects"
                + "\\FactoryManagement\\src\\main\\java\\com\\mycompany\\factorymanagement\\"
                + "icons\\managers.png";
        ImageIcon icon = new ImageIcon(path);
        picm.setIcon(icon);

        String path2 = "C:\\Users\\login\\OneDrive\\Documents\\"
                + "NetBeansProjects\\FactoryManagement\\src\\main\\java\\com"
                + "\\mycompany\\factorymanagement\\icons\\employee.png";
        ImageIcon icon2 = new ImageIcon(path2);
        pice.setIcon(icon2);

        String path3 = "C:\\Users\\login\\OneDrive\\Documents"
                + "\\NetBeansProjects\\FactoryManagement\\src\\main"
                + "\\java\\com\\mycompany\\factorymanagement\\icons\\product.png";
        ImageIcon icon3 = new ImageIcon(path3);
        pict.setIcon(icon3);
        
        String path4 = "C:\\Users\\login\\OneDrive\\Documents"
                + "\\NetBeansProjects\\FactoryManagement\\src\\main"
                + "\\java\\com\\mycompany\\factorymanagement\\icons\\Stock.png";
        ImageIcon icon4 = new ImageIcon(path4);
        pict1.setIcon(icon4);
        try {
               int count=0;

            String sql ="SELECT ID FROM users WHERE role=?";
            PreparedStatement ps = con.connection.prepareStatement(sql);
            ps.setInt(1,2);
            ResultSet  rs = ps.executeQuery();
            while(rs.next()){
                count++;
            }
            numm.setText(String.valueOf(count));
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
               int count=0;

            String sql ="SELECT ID FROM users WHERE role=?";
            PreparedStatement ps = con.connection.prepareStatement(sql);
            ps.setInt(1,3);
            ResultSet  rs = ps.executeQuery();
            while(rs.next()){
                count++;
            }
            numf.setText(String.valueOf(count));
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
               int count=0;

            String sql ="SELECT ID FROM products ";
            PreparedStatement ps = con.connection.prepareStatement(sql);
            ResultSet  rs = ps.executeQuery();
            while(rs.next()){
                count++;
            }
            nump.setText(String.valueOf(count));
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
               int count=0;

            String sql ="SELECT stock FROM stock ";
            PreparedStatement ps = con.connection.prepareStatement(sql);
            ResultSet  rs = ps.executeQuery();
            while(rs.next()){
                count+=rs.getDouble("stock");
            }
            numt.setText(String.valueOf(count));
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pica = new javax.swing.JPanel();
        picm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numm = new javax.swing.JLabel();
        picb = new javax.swing.JPanel();
        pice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numf = new javax.swing.JLabel();
        picc = new javax.swing.JPanel();
        pict = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nump = new javax.swing.JLabel();
        numt = new javax.swing.JLabel();
        picc1 = new javax.swing.JPanel();
        pict1 = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(883, 500));

        pica.setBackground(new java.awt.Color(255, 255, 255));

        picm.setBackground(new java.awt.Color(255, 255, 255));
        picm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout picaLayout = new javax.swing.GroupLayout(pica);
        pica.setLayout(picaLayout);
        picaLayout.setHorizontalGroup(
            picaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        picaLayout.setVerticalGroup(
            picaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picm, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Managers");

        numm.setBackground(new java.awt.Color(255, 255, 255));
        numm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numm.setText("jLabel5");

        picb.setBackground(new java.awt.Color(255, 255, 255));

        pice.setBackground(new java.awt.Color(255, 255, 255));
        pice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout picbLayout = new javax.swing.GroupLayout(picb);
        picb.setLayout(picbLayout);
        picbLayout.setHorizontalGroup(
            picbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        picbLayout.setVerticalGroup(
            picbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pice, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Foremans");

        numf.setBackground(new java.awt.Color(255, 255, 255));
        numf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numf.setText("jLabel5");

        picc.setBackground(new java.awt.Color(255, 255, 255));

        pict.setBackground(new java.awt.Color(255, 255, 255));
        pict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pictMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout piccLayout = new javax.swing.GroupLayout(picc);
        picc.setLayout(piccLayout);
        piccLayout.setHorizontalGroup(
            piccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pict, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        piccLayout.setVerticalGroup(
            piccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pict, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Products");

        nump.setBackground(new java.awt.Color(255, 255, 255));
        nump.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nump.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nump.setText("jLabel5");

        numt.setBackground(new java.awt.Color(255, 255, 255));
        numt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numt.setText("jLabel5");

        picc1.setBackground(new java.awt.Color(255, 255, 255));

        pict1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pict1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout picc1Layout = new javax.swing.GroupLayout(picc1);
        picc1.setLayout(picc1Layout);
        picc1Layout.setHorizontalGroup(
            picc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pict1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        picc1Layout.setVerticalGroup(
            picc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pict1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Stock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Stock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stock.setText("Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(picb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nump, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(picc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Stock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(picc1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(picc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(picc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nump, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(picb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(250, 250, 250))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(138, 50));

        jMenu1.setText("Profile ");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Foremans");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Managers");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Products");
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("All users ");
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Stock");
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Log Out");
        jMenu7.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu7MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Exit");
        jMenu8.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu8MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        View viwe = new View(adminData);
        viwe.setVisible(true);
        this.dispose();

        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        EmployeeTable addEmployee = new EmployeeTable(3, adminData);
        addEmployee.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        EmployeeTable addEmployee = new EmployeeTable(2, adminData);
        addEmployee.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        AddProduct product = new AddProduct(adminData);
        product.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        UsersTAble addEmployee = new UsersTAble(adminData);
        addEmployee.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
        AddStock product = new AddStock(adminData);
        product.setVisible(true);
        this.dispose();//          // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MenuSelected

    private void jMenu7MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu7MenuSelected
        int result = JOptionPane.showConfirmDialog(null, "Are You sure you want to SIGN OUT ?");
        switch (result) {
            case JOptionPane.YES_OPTION -> {
                LoginBefore login = new LoginBefore();
                login.setVisible(true);

                this.dispose();
                break;
            }
            case JOptionPane.NO_OPTION -> {
                break;
            }
            case JOptionPane.CANCEL_OPTION -> {
                break;
            }
            case JOptionPane.CLOSED_OPTION -> {
                break;
            }
        }              // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7MenuSelected

    private void jMenu8MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu8MenuSelected
        System.exit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu8MenuSelected

    private void picmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picmMouseClicked
EmployeeTable addEmployee = new EmployeeTable(2, adminData);
        addEmployee.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_picmMouseClicked

    private void piceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piceMouseClicked
EmployeeTable addEmployee = new EmployeeTable(3, adminData);
        addEmployee.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_piceMouseClicked

    private void pictMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pictMouseClicked
ProductTable employee = new ProductTable(adminData);

                    employee.setVisible(true);
                    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_pictMouseClicked

    private void pict1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pict1MouseClicked
 StockTable employee = new StockTable(adminData);
                employee.setVisible(true);
                this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_pict1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Stock;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numf;
    private javax.swing.JLabel numm;
    private javax.swing.JLabel nump;
    private javax.swing.JLabel numt;
    private javax.swing.JPanel pica;
    private javax.swing.JPanel picb;
    private javax.swing.JPanel picc;
    private javax.swing.JPanel picc1;
    private javax.swing.JLabel pice;
    private javax.swing.JLabel picm;
    private javax.swing.JLabel pict;
    private javax.swing.JLabel pict1;
    // End of variables declaration//GEN-END:variables
}
